application:
  port: 8000
database:
  host: 127.0.0.1
  name: newsletter
  password: password
  port: 5432
  username: postgres
  require_ssl: false
email_client:
  authorization_token: "my-fake-auth-token"
  base_url: "localhost"
  sender_email: "test@gmail.com"
  timeout_milliseconds: 10000
